version: '3.9'

services:
  vueapp:
    image: "vueapphealthylink"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vueapp
    ports:
      - 5173:80
  
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - vueapp